{
	"lastUpdatedUtc": "2016-02-28T16:41:41.090Z",
	"createdDateUtc": "2016-02-28T16:41:41.090Z",
	"scheduledAiringId": "157581969",
	"programFoxipediaId": "SER000594PPMW",
	"scheduledAiringNetworkCallLetter": "FS1",
	"scheduledAiringNetworkName": "FOX SPORTS RACING",
	"scheduledAiringNetworkShortName": "FSR",
	"seasonFoxipediaId": "SEA000599PPMW",
	"episodeFoxipediaId": "EPI006964PPMW",
	"deliveryMethod": "Fiber",
	"broadcastAirDate": "2016-02-28T16:41:41.090Z",
	"scheduledAiringStartTimeUTC": "2016-02-28T16:41:41.090Z",
	"scheduledAiringDuration": "1800000",
	"fillTime": 54000,
	"closedCaptioning": "yes",
	"Live": "true",
	"territoryNames": [
		"FSRCanada",
		"FSRCarribbean"
	],
	"format": "HD/HD 1010",
	"fsnFormatName": " ",
	"materialID": "F12AMD1096",
	"programSupplier": "",
	"sap": "Audio Description",
	"dvs": "yes",
	"logType": "Primary",
	"status": "Scheduled",
	"joinInProgressFlag": false,
	"updateType": "Added",
	"tmsId": "SH007685450000",
	"Path": 1010,
  "programTitle":"Big Ten Elite",
	"programDescription":"Germany's premier soccer league. Delayed matches coming from FOX Sports 1"
}