#%RAML 1.0 SecurityScheme
#=======================================================================
# Standard Basic Authentication Security Scheme
# SecuritySchemes/standard-security-scheme.raml
# Date   : February 05, 2020
# Author : RIEDEL
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 RAR   05-Feb-2020 Initial creation
#=======================================================================
type: Basic Authentication
description: Use application client_id and secret assigned by API administrator.