#%RAML 1.0 Trait
#=======================================================================
# Standard Client Authorization Header
# Traits/standard-client-authorization.raml
# Date   : February 05, 2020
# Author : RIEDEL
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 RAR   05-Feb-2020 Initial creation
#=======================================================================
usage: Client Authorization Required Trait
    
headers:
  Authorization:
    type: string
    example: Basic YjFjNGRlMmM4YTQ4NDk5M2IwNTc5ZDg1YzU0ZjRjNDM6ZEIxNUY1MWY0MjZBNEExNDkwOWQzMGJEQWFhMURFMmQ=
  authorization:
    type: string
    example: Basic YjFjNGRlMmM4YTQ4NDk5M2IwNTc5ZDg1YzU0ZjRjNDM6ZEIxNUY1MWY0MjZBNEExNDkwOWQzMGJEQWFhMURFMmQ=     
