#%RAML 1.0 Trait
#=======================================================================
# Standard Client Authorization Header
# Traits/standard-client-authorization.raml
# Date   : JUNE 06, 2020
# Author : SANKAR
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 SAN   06-JUN-2020 Initial creation
#=======================================================================
usage: Client Authorization Using Header Required Trait

headers:
  client_id:
    type: string
    example: YjFjNGRlMmM4YTQ4NDk5M2IwNT
  client_secret:
    type: string
    example: YjFjNGRlMmM4YTQ4NDk5M2IwNT

