#%RAML 1.0 Trait
#=======================================================================
# Standard Client Authorization Header
# Traits/standard-client-authorization.raml
# Date   : April 16, 2020
# Author : BKWON
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 BYK   16-Apr-2020 Initial creation
#=======================================================================
usage: Client Authorization Required Trait
    
headers:
  Authorization:
    type: string
    example: Bearer eyJraWQiOiJ0bDYxRVdZUHVUbDV1RmI1aDAwQkFaelBKeWs1dXdzc09aREc4R2lwVkRBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnFpOG9BWmxzcXlPWW9rUnlxQ3dROWlTWDl0a3BwZV9EblpoT0FyekZkWGciLCJpc3MiOiJodHRwczovL215Zm94Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzcHFpaXdueGVmSVNnYXAwaDciLCJhdWQiOiJtdWxlc29mdE9BdXRoIiwiaWF0IjoxNTgyMDQ3NDUyLCJleHAiOjE1ODIwNjE4NTIsImNpZCI6IjBvYXB0N2h6NTJaVFFFZEJiMGg3Iiwic2NwIjpbImRlZmF1bHQiXSwic3ViIjoiMG9hcHQ3aHo1MlpUUUVkQmIwaDcifQ.BM-gulHHSsdbPAxku9tADsC5BTYfYsiMsFWNIILPoYsvJ4J5zs3cma7u2jssBTQ2D9VrQrkUofSkwI2ODtxgV3YHOv3-9MzpZudojFIT6v_z5SWsktiHKqjj4-drFUBeoB8FswUttHXBkg1YKRiViDcfmyJEmEw1phCw2ZT-6fK2sRzDgoT6mUNnLZSBY6SdOV1AQLaD6niI8yHvAZwHWxeoVQohFR2NmKz6c2mTW1-02f0_uWI25opk9YlCUdkjC2_s6SUoNdT4G62cc54vhobIzde3lokiGTdk13oBfK_vwxiRlql-n1dwbH-ZjHW0GC3Ji5HhmnfiXCsIsK2iZA
  authorization:
    type: string
    example: Bearer eyJraWQiOiJ0bDYxRVdZUHVUbDV1RmI1aDAwQkFaelBKeWs1dXdzc09aREc4R2lwVkRBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnFpOG9BWmxzcXlPWW9rUnlxQ3dROWlTWDl0a3BwZV9EblpoT0FyekZkWGciLCJpc3MiOiJodHRwczovL215Zm94Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzcHFpaXdueGVmSVNnYXAwaDciLCJhdWQiOiJtdWxlc29mdE9BdXRoIiwiaWF0IjoxNTgyMDQ3NDUyLCJleHAiOjE1ODIwNjE4NTIsImNpZCI6IjBvYXB0N2h6NTJaVFFFZEJiMGg3Iiwic2NwIjpbImRlZmF1bHQiXSwic3ViIjoiMG9hcHQ3aHo1MlpUUUVkQmIwaDcifQ.BM-gulHHSsdbPAxku9tADsC5BTYfYsiMsFWNIILPoYsvJ4J5zs3cma7u2jssBTQ2D9VrQrkUofSkwI2ODtxgV3YHOv3-9MzpZudojFIT6v_z5SWsktiHKqjj4-drFUBeoB8FswUttHXBkg1YKRiViDcfmyJEmEw1phCw2ZT-6fK2sRzDgoT6mUNnLZSBY6SdOV1AQLaD6niI8yHvAZwHWxeoVQohFR2NmKz6c2mTW1-02f0_uWI25opk9YlCUdkjC2_s6SUoNdT4G62cc54vhobIzde3lokiGTdk13oBfK_vwxiRlql-n1dwbH-ZjHW0GC3Ji5HhmnfiXCsIsK2iZA     
