#%RAML 1.0 Trait
#=======================================================================
# Standard Accept Header
# Traits/standard-accept-trait.raml
# Date   : JUNE 06, 2020
# Author : SANKAR
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 RAR   06-JUN-2020 Initial creation
#   002 SAN   06-Jun-2020 Optional Details section added
#=======================================================================
usage: Accept Required Trait

headers:
  x-correlation-id:
    type: string
    required: false
