#%RAML 1.0 Trait
#=======================================================================
# Standard Content-Type Header
# Traits/standard-content-type.raml
# Date   : February 05, 2020
# Author : RIEDEL
# Rev    : 1
#
#  Audit History:
#
#   Rev Who   Date        Description
#   --- ---   ----------- ----------------------------------------------
#   001 RAR   05-Feb-2020 Initial creation
#=======================================================================
usage: Content Type Required Trait
headers: 
  Content-Type:
    type: string
    example: application/json
